const data = {
  products: [
    {
      id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: require("./Components/Assets/Images/p1.jpg"),
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: require("./Components/Assets/Images/p2.jpg"),
      price: 100,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: require("./Components/Assets/Images/p3.jpg"),
      price: 220,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: require("./Components/Assets/Images/p4.jpg"),
      price: 78,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      id: "5",
      name: "Puma Slim Pant",
      category: "Pants",
      image: require("./Components/Assets/Images/p5.jpg"),
      price: 65,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "6",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: require("./Components/Assets/Images/p6.jpg"),
      price: 139,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};

export default data;
